//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTecnico.WSForAddresses {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSForAddresses.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento calle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insDireccion", ReplyAction="*")]
        ServicioTecnico.WSForAddresses.insDireccionResponse insDireccion(ServicioTecnico.WSForAddresses.insDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insDireccion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioTecnico.WSForAddresses.insDireccionResponse> insDireccionAsync(ServicioTecnico.WSForAddresses.insDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reparaciones del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarDetalle", ReplyAction="*")]
        ServicioTecnico.WSForAddresses.InsertarDetalleResponse InsertarDetalle(ServicioTecnico.WSForAddresses.InsertarDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioTecnico.WSForAddresses.InsertarDetalleResponse> InsertarDetalleAsync(ServicioTecnico.WSForAddresses.InsertarDetalleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insDireccion", Namespace="http://tempuri.org/", Order=0)]
        public ServicioTecnico.WSForAddresses.insDireccionRequestBody Body;
        
        public insDireccionRequest() {
        }
        
        public insDireccionRequest(ServicioTecnico.WSForAddresses.insDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string calle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string colonia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cp;
        
        public insDireccionRequestBody() {
        }
        
        public insDireccionRequestBody(string calle, string numero, string colonia, string ciudad, string estado, string cp) {
            this.calle = calle;
            this.numero = numero;
            this.colonia = colonia;
            this.ciudad = ciudad;
            this.estado = estado;
            this.cp = cp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioTecnico.WSForAddresses.insDireccionResponseBody Body;
        
        public insDireccionResponse() {
        }
        
        public insDireccionResponse(ServicioTecnico.WSForAddresses.insDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insDireccionResult;
        
        public insDireccionResponseBody() {
        }
        
        public insDireccionResponseBody(int insDireccionResult) {
            this.insDireccionResult = insDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarDetalle", Namespace="http://tempuri.org/", Order=0)]
        public ServicioTecnico.WSForAddresses.InsertarDetalleRequestBody Body;
        
        public InsertarDetalleRequest() {
        }
        
        public InsertarDetalleRequest(ServicioTecnico.WSForAddresses.InsertarDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long idservicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int empleadoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaRev;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reparaciones;
        
        public InsertarDetalleRequestBody() {
        }
        
        public InsertarDetalleRequestBody(long idservicio, int empleadoId, System.DateTime fechaRev, string reparaciones) {
            this.idservicio = idservicio;
            this.empleadoId = empleadoId;
            this.fechaRev = fechaRev;
            this.reparaciones = reparaciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarDetalleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioTecnico.WSForAddresses.InsertarDetalleResponseBody Body;
        
        public InsertarDetalleResponse() {
        }
        
        public InsertarDetalleResponse(ServicioTecnico.WSForAddresses.InsertarDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarDetalleResult;
        
        public InsertarDetalleResponseBody() {
        }
        
        public InsertarDetalleResponseBody(string InsertarDetalleResult) {
            this.InsertarDetalleResult = InsertarDetalleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ServicioTecnico.WSForAddresses.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ServicioTecnico.WSForAddresses.WebServiceSoap>, ServicioTecnico.WSForAddresses.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioTecnico.WSForAddresses.insDireccionResponse ServicioTecnico.WSForAddresses.WebServiceSoap.insDireccion(ServicioTecnico.WSForAddresses.insDireccionRequest request) {
            return base.Channel.insDireccion(request);
        }
        
        public int insDireccion(string calle, string numero, string colonia, string ciudad, string estado, string cp) {
            ServicioTecnico.WSForAddresses.insDireccionRequest inValue = new ServicioTecnico.WSForAddresses.insDireccionRequest();
            inValue.Body = new ServicioTecnico.WSForAddresses.insDireccionRequestBody();
            inValue.Body.calle = calle;
            inValue.Body.numero = numero;
            inValue.Body.colonia = colonia;
            inValue.Body.ciudad = ciudad;
            inValue.Body.estado = estado;
            inValue.Body.cp = cp;
            ServicioTecnico.WSForAddresses.insDireccionResponse retVal = ((ServicioTecnico.WSForAddresses.WebServiceSoap)(this)).insDireccion(inValue);
            return retVal.Body.insDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioTecnico.WSForAddresses.insDireccionResponse> ServicioTecnico.WSForAddresses.WebServiceSoap.insDireccionAsync(ServicioTecnico.WSForAddresses.insDireccionRequest request) {
            return base.Channel.insDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioTecnico.WSForAddresses.insDireccionResponse> insDireccionAsync(string calle, string numero, string colonia, string ciudad, string estado, string cp) {
            ServicioTecnico.WSForAddresses.insDireccionRequest inValue = new ServicioTecnico.WSForAddresses.insDireccionRequest();
            inValue.Body = new ServicioTecnico.WSForAddresses.insDireccionRequestBody();
            inValue.Body.calle = calle;
            inValue.Body.numero = numero;
            inValue.Body.colonia = colonia;
            inValue.Body.ciudad = ciudad;
            inValue.Body.estado = estado;
            inValue.Body.cp = cp;
            return ((ServicioTecnico.WSForAddresses.WebServiceSoap)(this)).insDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioTecnico.WSForAddresses.InsertarDetalleResponse ServicioTecnico.WSForAddresses.WebServiceSoap.InsertarDetalle(ServicioTecnico.WSForAddresses.InsertarDetalleRequest request) {
            return base.Channel.InsertarDetalle(request);
        }
        
        public string InsertarDetalle(long idservicio, int empleadoId, System.DateTime fechaRev, string reparaciones) {
            ServicioTecnico.WSForAddresses.InsertarDetalleRequest inValue = new ServicioTecnico.WSForAddresses.InsertarDetalleRequest();
            inValue.Body = new ServicioTecnico.WSForAddresses.InsertarDetalleRequestBody();
            inValue.Body.idservicio = idservicio;
            inValue.Body.empleadoId = empleadoId;
            inValue.Body.fechaRev = fechaRev;
            inValue.Body.reparaciones = reparaciones;
            ServicioTecnico.WSForAddresses.InsertarDetalleResponse retVal = ((ServicioTecnico.WSForAddresses.WebServiceSoap)(this)).InsertarDetalle(inValue);
            return retVal.Body.InsertarDetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioTecnico.WSForAddresses.InsertarDetalleResponse> ServicioTecnico.WSForAddresses.WebServiceSoap.InsertarDetalleAsync(ServicioTecnico.WSForAddresses.InsertarDetalleRequest request) {
            return base.Channel.InsertarDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioTecnico.WSForAddresses.InsertarDetalleResponse> InsertarDetalleAsync(long idservicio, int empleadoId, System.DateTime fechaRev, string reparaciones) {
            ServicioTecnico.WSForAddresses.InsertarDetalleRequest inValue = new ServicioTecnico.WSForAddresses.InsertarDetalleRequest();
            inValue.Body = new ServicioTecnico.WSForAddresses.InsertarDetalleRequestBody();
            inValue.Body.idservicio = idservicio;
            inValue.Body.empleadoId = empleadoId;
            inValue.Body.fechaRev = fechaRev;
            inValue.Body.reparaciones = reparaciones;
            return ((ServicioTecnico.WSForAddresses.WebServiceSoap)(this)).InsertarDetalleAsync(inValue);
        }
    }
}
